name: Publish to NPM
on:
  push:
    branches: [publish-pipeline]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies and build 🔧
        run:  |
          if [ -e yarn.lock ]; then
          corepack enable && yarn install && yarn build
          elif [ -e package-lock.json ]; then
          npm ci && npm run build
          else
          npm i
          fi
      - name: Publish package on NPM 📦
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
